app:
  title: "Sentinel RAG System"
  description: "Solid MVP with Session RAG"
  log_level: "INFO"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(funcName)s - %(message)s"

llm:
  # provider: "ollama", "openai"
  provider: "openai"
  model_name: "gpt-4o"
  # api_base: "https://api.groq.com/openai/v1" # 필요시 활성화
  temperature: 0

embedding:
  provider: "ollama"
  model_name: "nomic-embed-text"

vector_store:
  provider: "pg_vector"

reranker:
  provider: "none"
  # provider: "cross_encoder"
  # model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"